import React from "react";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css';
import '~/css/novstyle.css';
import '~/css/icon_fonts.css'
import '~/css/font-awesome.min.css'
import '~/css/material-design-iconic-font.min.css'
import '~/css/base.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href='https://fonts.googleapis.com/css?family=Signika' rel='stylesheet' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
